spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true